# Generated by Django 2.1.7 on 2019-02-26 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('blogs', '0001_initial'), ('blogs', '0002_auto_20190224_1456'), ('blogs', '0003_auto_20190224_1501'), ('blogs', '0004_remove_blogs_delete'), ('blogs', '0005_auto_20190224_1530')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('body', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('blog_category', models.CharField(choices=[('Political', 'Political'), ('Movies', 'Movies'), ('World War', 'World War')], db_index=True, default='World War', max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
