# Generated by Django 2.1.7 on 2019-02-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_pub_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='pub_status',
            new_name='published',
        ),
    ]
