# Generated by Django 2.1.7 on 2019-02-27 14:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
