# Generated by Django 2.1.7 on 2019-02-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190222_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='status',
            new_name='delete',
        ),
    ]
