# Generated by Django 2.1.7 on 2019-02-27 17:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190227_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='summary1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
