# Generated by Django 2.1.7 on 2019-02-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190224_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='delete',
        ),
    ]
