# Generated by Django 2.1.7 on 2019-02-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blogs_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_category',
            field=models.CharField(choices=[('Political', 'Political'), ('Movies', 'Movies'), ('World War', 'World War')], db_index=True, default='World War', max_length=25),
        ),
    ]
