# Generated by Django 2.1.7 on 2019-02-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190222_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='delete',
            field=models.IntegerField(default=0),
        ),
    ]
