# Generated by Django 2.1.7 on 2019-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190222_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
